GO
 
IF  EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Fn_ErrorFetch]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[Fn_ErrorFetch]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[Fn_ErrorFetch](@SPID Varchar(MAX))
  
AS
BEGIN
  DELETE FROM TBL_ERRORFETCH

  INSERT INTO TBL_ERRORFETCH (EVENTTYPE,PARAMS,PIN)
  EXEC('DBCC INPUTBUFFER('+@SPID+') WITH NO_INFOMSGS')

END
GO
