GO
 
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TBL_ERRORFETCH]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[TBL_ERRORFETCH](
	[EVENTTYPE] [varchar](max) NULL,
	[PARAMS] [varchar](max) NULL,
	[PIN] [varchar](max) NULL
) ON [PRIMARY]
END
GO
SET ANSI_PADDING OFF
GO
